replicaCount: 1
image:
  repository: 900603399370.dkr.ecr.ap-northeast-2.amazonaws.com/membership-service-devops
  pullPolicy: IfNotPresent
  tag: "f92251dcb01578ce7b5be76248cf0fa1b77b404f"
fullnameOverride: "dev-membership-service"
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - paths:
        - path: /
          pathType: Prefix
env: dev
